#lang racket/base

#|\begin{math}
sin x = 3 sin(x/3) - 4 sin^3(x/3)
\end{math}|#

(define (cube x) (* x x x))

;; In the book it's named `p', but I wanted it to stand out more.
;; Also, I wanted to demonstrate just how liberal Scheme is w/r/t
;; naming identifiers.
(define ($! x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (0.1 . < . (abs angle)))
      angle
      ($! (sine (angle . / . 3.0)))))

; How many times is p applied when (sine 12.15) is evaluated?
;; (sine 12.15)
;; => ($! (sine 4.05))
;; => ($! ($! (sine 1.35)))
;; => ($! ($! ($! (sine 0.45))))
;; => ($! ($! ($! ($! (sine 0.15)))))
;; => ($! ($! ($! ($! ($! (sine 0.05))))))
;; => ($! ($! ($! ($! ($! 0.05)))))
;; => ...etc...
;the important thing is that we can see that the function in
;question was applied 5 times.


; What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?
;; both by log-base-three?
